function(darknet_resolve_precision_architectures architectures native_compute_capability out_fp8 out_fp4 out_sm89 out_resolved out_fp8_architectures out_fp4_architectures)
	if("${architectures}" STREQUAL "")
		message(FATAL_ERROR "CUDA architecture list must not be empty")
	endif()
	set(resolved_architectures "")
	set(fp8_architectures "")
	set(fp4_architectures "")
	set(has_fp8 OFF)
	set(has_fp4 OFF)
	set(has_sm89 OFF)

	foreach(architecture IN LISTS architectures)
		string(TOLOWER "${architecture}" architecture_lower)
		set(candidate_numbers "")
		set(candidate_targets "")
		if(architecture_lower STREQUAL "native")
			if("${native_compute_capability}" STREQUAL "")
				message(FATAL_ERROR "CUDA architecture 'native' requires at least one numeric native compute capability")
			endif()
			foreach(native_architecture IN LISTS native_compute_capability)
				if(NOT native_architecture MATCHES "^[0-9]+$")
					message(FATAL_ERROR "CUDA architecture 'native' requires numeric native compute capabilities")
				endif()
				list(APPEND candidate_numbers "${native_architecture}")
				list(APPEND candidate_targets "${native_architecture}")
			endforeach()
		else()
			if(NOT architecture_lower MATCHES "^([0-9]+)(-(real|virtual))?$")
				message(FATAL_ERROR "Unsupported CUDA architecture entry: ${architecture}")
			endif()
			list(APPEND candidate_numbers "${CMAKE_MATCH_1}")
			list(APPEND candidate_targets "${architecture}")
		endif()

		# Classify each resolved (number, target) pair exactly once, whether it came from
		# expanding "native" into one or more compute capabilities, or from a single
		# explicit architecture entry.
		list(LENGTH candidate_numbers candidate_count)
		math(EXPR candidate_last "${candidate_count} - 1")
		foreach(candidate_index RANGE ${candidate_last})
			list(GET candidate_numbers ${candidate_index} architecture_number)
			list(GET candidate_targets ${candidate_index} architecture_target)

			list(APPEND resolved_architectures "${architecture_target}")
			if(architecture_number GREATER_EQUAL 89)
				set(has_fp8 ON)
				list(APPEND fp8_architectures "${architecture_target}")
			endif()
			if(architecture_number STREQUAL "89")
				set(has_sm89 ON)
			endif()
			if(architecture_number STREQUAL "100" OR
			   architecture_number STREQUAL "103" OR
			   architecture_number STREQUAL "110" OR
			   architecture_number STREQUAL "120" OR
			   architecture_number STREQUAL "121")
				set(has_fp4 ON)
				list(APPEND fp4_architectures "${architecture_target}")
			endif()
		endforeach()
	endforeach()

	list(REMOVE_DUPLICATES resolved_architectures)
	list(REMOVE_DUPLICATES fp8_architectures)
	list(REMOVE_DUPLICATES fp4_architectures)
	set(${out_fp8} "${has_fp8}" PARENT_SCOPE)
	set(${out_fp4} "${has_fp4}" PARENT_SCOPE)
	set(${out_sm89} "${has_sm89}" PARENT_SCOPE)
	set(${out_resolved} "${resolved_architectures}" PARENT_SCOPE)
	set(${out_fp8_architectures} "${fp8_architectures}" PARENT_SCOPE)
	set(${out_fp4_architectures} "${fp4_architectures}" PARENT_SCOPE)
endfunction()

function(darknet_validate_tristate variable_name)
	string(TOUPPER "${${variable_name}}" normalized_value)
	if(NOT normalized_value MATCHES "^(AUTO|ON|OFF)$")
		message(FATAL_ERROR "${variable_name} must be AUTO, ON, or OFF (got '${${variable_name}}')")
	endif()
	set(${variable_name} "${normalized_value}" PARENT_SCOPE)
endfunction()

function(darknet_resolve_precision_feature requested compatible feature_name out_enabled)
	darknet_validate_tristate(requested)
	if(requested STREQUAL "ON" AND NOT compatible)
		message(FATAL_ERROR "${feature_name}=ON requires at least one compatible CUDA architecture")
	endif()
	if(requested STREQUAL "OFF")
		set(enabled OFF)
	elseif(compatible)
		set(enabled ON)
	else()
		set(enabled OFF)
	endif()
	set(${out_enabled} "${enabled}" PARENT_SCOPE)
endfunction()
