/* Darknet/YOLO:  https://codeberg.org/iltranqu/darknet
 * Ouroboros recursive block, Stage 1 FiLM/gate + Stage 2 Conv-LoRA patch.
 */

#pragma once

#ifndef __cplusplus
#error "The Darknet/YOLO project requires a C++ compiler."
#endif

#include "darknet_internal.hpp"

/** @file
 * Recursive/recurrent-depth block layer.  Optionally, the hidden state can be
 * projected through a finite candidate lattice between passes, following the
 * Lattice Deduction Transformer idea of alternating a recurrent transformer
 * step with a lattice-valued deduction state.
 *
 * Stage 0 compatibility:
 * - ouroboros=0 keeps the old static recurrence:
 *     next = body_scale * body(h) + residual_scale * h + injection_scale * input
 *
 * Stage 1 Ouroboros-lite:
 * - ouroboros=1 enables a tiny trainable controller over GAP(hidden) + step_scalar.
 * - The controller emits per-channel gamma and gate values.
 * - The body may still be ordinary Darknet [convolutional] layers.
 * - The recurrence becomes:
 *     candidate = adapted(body(h)) * body_scale
 *     gamma, gate = controller(GAP(h), step)
 *     next = gate * candidate * (1 + gamma) + (1 - gate) * h
 *   Optional injection still adds injection_scale * original_input when shortcut=1.
 *
 * Stage 2 Conv-LoRA:
 * - ouroboros=2 keeps the Stage 1 FiLM/gated recurrence and additionally wraps
 *   eligible convolutional body layers with dynamic low-rank adapters:
 *     y = Conv_base(x) + (lora_alpha / lora_rank) * Conv_B( diag_t * Conv_A(x) )
 * - diag_t is generated by the same controller from GAP(hidden) + step_scalar.
 * - Base body convolutional weights can be frozen with lora_freeze_base=1 while
 *   controller/A/B adapter weights train.
 * - The Stage 1 path remains available with ouroboros=1.
 *
 * Cfg example:
 * @code
 * [recursive_block]
 * loops=4
 * body=2
 * injection=0
 * body_scale=1.0
 * residual_scale=0.0
 * injection_scale=0.0
 * ouroboros=1
 * gate_bias=-2.0
 * gamma_clip=4.0
 * gate_clip=30.0
 *
 * # Optional LDT-style lattice projection between passes.
 * # Requires parser hookup via set_recursive_block_lattice_projection().
 * # lattice_group channels must divide c if > 1.
 * # lattice_group=8
 * # lattice_threshold=0.10
 * # lattice_temperature=1.0
 * # lattice_mix=1.0
 *
 * # Stage 2 alternative:
 * # ouroboros=2
 * # lora_rank=16
 * # lora_alpha=16
 * # lora_freeze_base=1
 * # lora_diag_init=1.0
 * # lora_diag_clip=4.0
 *
 * [convolutional]
 * filters=256
 * size=3
 * pad=1
 * batch_normalize=0
 * activation=leaky
 *
 * [convolutional]
 * filters=256
 * size=3
 * pad=1
 * batch_normalize=0
 * activation=leaky
 * @endcode
 */

Darknet::Layer make_recursive_block_layer(int batch, int h, int w, int c, int loops, int shortcut,
	float body_scale, float residual_scale, float injection_scale, int train);

void finalize_recursive_block_layer(Darknet::Layer * l);

/** Enable LDT-style lattice projection between recursive passes.
 *
 * Stores settings in existing generic Layer fields (no weight format change):
 * - l.alpha  = mix (0 = disabled, 1 = fully replace hidden state)
 * - l.beta   = elimination_threshold (~0.1)
 * - l.scale  = sigmoid temperature for alive-probability mapping
 * - l.groups = candidate_group (channels per lattice cell; must divide l.c if > 1)
 *
 * Applied only between non-final passes, not to the visible output.
 */
void set_recursive_block_lattice_projection(Darknet::Layer * l, int candidate_group, float elimination_threshold, float temperature, float mix);

void free_recursive_block_layer(Darknet::Layer & l);
void resize_recursive_block_layer(Darknet::Layer * l, int w, int h);

void forward_recursive_block_layer (Darknet::Layer & l, Darknet::NetworkState state);
void backward_recursive_block_layer(Darknet::Layer & l, Darknet::NetworkState state);
void update_recursive_block_layer  (Darknet::Layer & l, int batch, float learning_rate, float momentum, float decay);

#ifdef DARKNET_GPU
void forward_recursive_block_layer_gpu (Darknet::Layer & l, Darknet::NetworkState state);
void backward_recursive_block_layer_gpu(Darknet::Layer & l, Darknet::NetworkState state);
void update_recursive_block_layer_gpu  (Darknet::Layer & l, int batch, float learning_rate, float momentum, float decay, float loss_scale);
void push_recursive_block_layer(Darknet::Layer & l);
void pull_recursive_block_layer(Darknet::Layer & l);
#endif
